# Generated by Django 3.1.1 on 2020-09-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0007_auto_20200907_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='maximumclick',
            name='diamonds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maximumclick',
            name='golds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
