# Generated by Django 3.1.1 on 2020-09-04 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameGenerator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(default='Gold Mine', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.CharField(default='Gold', max_length=10)),
                ('game', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='gold_app.gamegenerator')),
            ],
        ),
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamond', models.CharField(max_length=10, unique=True)),
                ('game', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='gold_app.gamegenerator')),
            ],
        ),
        migrations.CreateModel(
            name='Bomb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bomb', models.CharField(default='Bomb', max_length=10)),
                ('game', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='gold_app.gamegenerator')),
            ],
        ),
    ]
