# Generated by Django 3.1.1 on 2020-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0002_auto_20200904_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegenerator',
            name='bombs',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='gamegenerator',
            name='diamonds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamegenerator',
            name='golds',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='gamegenerator',
            name='max_platform',
            field=models.IntegerField(default=100),
        ),
    ]
