# Generated by Django 3.1.1 on 2020-09-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0008_auto_20200909_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maximumclick',
            name='diamonds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maximumclick',
            name='golds',
            field=models.IntegerField(default=0),
        ),
    ]
